queries.load(new InputStreamReader(input, StandardCharsets.UTF_8));

sql.FIND_ALL_client = SELECT * FROM Client
sql.UPDATE_client = UPDATE Client SET first_name = ?, last_name = ?, middle_name = ?, phone_number = ?, email = ?, birth_date = ?, preferences = ? WHERE client_id = ?
sql.INSERT_client = INSERT INTO Client (first_name, last_name, middle_name, phone_number, email, birth_date, preferences) VALUES (?, ?, ?, ?, ?, ?, ?);
sql.DELETE_client = DELETE FROM Client WHERE client_id = ?


sql.FIND_ALL_appointment = SELECT * FROM Appointment
sql.UPDATE_appointment = UPDATE Appointment SET client_id = ?, master_id = ?, appointment_date = ?, appointment_time = ?, status = ? WHERE appointment_id = ?
sql.INSERT_appointment = INSERT INTO Appointment (client_id, master_id, appointment_date, appointment_time, status) VALUES (?, ?, ?, ?, ?);
sql.DELETE_appointment = DELETE FROM Appointment WHERE appointment_id = ?
sql.FIND_appointment = SELECT * FROM get_planned_appointments();

sql.CompleteAppointment_appointment = UPDATE appointment SET status = '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043D\u0430' WHERE appointment_id = ?
sql.cancelAppointment_appointment = UPDATE appointment SET status = '\u041E\u0442\u043C\u0435\u043D\u0435\u043D\u0430' WHERE appointment_id = ?

sql.FIND_ALL_master = SELECT * FROM get_masters_with_services();
sql.UPDATE_master = UPDATE Master SET first_name = ?, last_name = ?, middle_name = ?, phone_number = ?, specialization = ?, work_schedule = ? WHERE master_id = ?
sql.INSERT_master = INSERT INTO Master (first_name, last_name, middle_name, phone_number, specialization, work_schedule) VALUES (?, ?, ?, ?, ?, ?);
sql.DELETE_master = DELETE FROM Master WHERE master_id = ?

sql.FIND_ALL_material = SELECT * FROM Material
sql.UPDATE_material = UPDATE Material SET name = ?, quantity_on_hand = ?  WHERE material_id = ?
sql.INSERT_material = INSERT INTO Material (name, quantity_on_hand) VALUES (?, ?, ?);
sql.DELETE_material = DELETE FROM Material WHERE material_id = ?

sql.FIND_ALL_receipt = SELECT * FROM Receipt
sql.UPDATE_receipt  = UPDATE Receipt SET appointment_id = ?, total_amount = ?, payment_status = ?, payment_method = ?, receipt_date = ? WHERE receipt_id = ?
sql.INSERT_receipt  = INSERT INTO Receipt (appointment_id, total_amount, payment_status, payment_method, receipt_date) VALUES (?, ?, ?, ?, ?);
sql.DELETE_receipt  = DELETE FROM Receipt WHERE receipt_id = ?

sql.schedule_getMasterWeekSchedule = SELECT * FROM get_master_week_schedule(?, ?);
sql.schedule_getMasterDaySchedule  = SELECT * FROM get_master_day_schedule(?, ?, ?);

sql.FIND_ALL_service = SELECT * FROM Service
sql.UPDATE_service  = UPDATE Service SET name = ?, duration = ?, price = ?, masterId = ? WHERE serviceId = ?
sql.INSERT_service  = INSERT INTO Service (name, duration, price, masterId) VALUES (?, ?, ?, ?);
sql.DELETE_service  = DELETE FROM Service WHERE serviceId = ?
